### ISSUE TITLE
Refresh list of "Your liquidity"

### ISSUE THREAD

**Issue by cbcrypto101** [Pusher-Labs/asgard-exchange#57]
When finished adding liquidity the "Your liquidity" list is still empty. A manual refresh has to be done. This can create a lot of confusion for users.

Add an automatic refresh of the list when "adding liquidity transactions" are successful, or when the screen "Pool" is opened.

**Comment by stuartkuentzel** [comment]
@cbcrypto101 you're right, landing some confused users. one of the issues with this is that it looks like the midgard API caches specific staker info.

For example, let's say I have no pools listed. One page load, it hits midgard, which returns no pools. Then I successfully deposit to a pool. After the deposit is successful, I query the same endpoint for user pools. That still will return an empty array. If I then query the endpoint a third time, the pool will appear.

A couple solutions for this...
- Wait for midgard updates / midgard 2
- Continuously poll that user pools endpoint. The issue here is, say we poll every 30 seconds. Even after a successful transaction, it will still take a minute to appear due to midgard caching.

**Comment by stuartkuentzel** [comment]
this should be fixed in the recently merged feat/native-rune branch. On balance change, it refreshes the pool list twice, once to break the cache, second time gets the data
